# Image Version
ARG IMAGE_VERSION=v4.99.0

# Use base image without Java
FROM quay.io/gpte-devops-automation/codeserver:${IMAGE_VERSION}

# Software versions
ARG BUILD_DATE="2025-04-19"
ARG JAVA_VERSION="21"

LABEL name="Code Server - Developer IDE" \
      vendor="Code Server" \
      io.k8s.display-name="Code Server - Developer IDE" \
      io.openshift.expose-services="8080,codeserver" \
      io.openshift.tags="codeserver" \
      build-date=$BUILD_DATE \
      version=$IMAGE_VERSION \
      java-version=$JAVA_VERSION \
      release="1" \
      maintainer="Wolfgang Kulhanek <wkulhanek@redhat.com>"

USER root
RUN dnf -y install java-$JAVA_VERSION-openjdk java-$JAVA_VERSION-openjdk-devel && \
    rm -rf /var/cache/dnf /root/.cache

USER codeserver
